Adding tmt tier-0 test
containers/initoverlayfs pull request #28
Opened 2023-11-30 17:19 UTC by Yarboa

Tests are run by packit through tmt in testsing-farm Adding integration plan and tier-0 test verifying
initoverlayfs setup

2023-11-30 17:24 UTC, ericcurtin commented
This is really neat @Yarboa

2023-11-30 17:25 UTC, ericcurtin approved these changes

2023-11-30 18:32 UTC, dougsland commented
LGTM

2023-12-01 17:34 UTC, ericcurtin commented
This should work after we merge this I think:

https://github.com/containers/initoverlayfs/pull/30

we need PR number 30 anyway for unaccounted devices.

2023-12-04 11:53 UTC, lsm5 requested changes

2023-12-04 11:53 UTC, lsm5 commented on .packit.yaml
> +upstream_tag_template: v{version}
remove line 6 entirely. Given the version tagged doesn't begin with `v`, packit can just use the defaults.

That's currently causing the build failure as seen at https://copr.fedorainfracloud.org/coprs/packit/containers-initoverlayfs-28/build/6721833/

2023-12-07 14:20 UTC, mwperina approved these changes
LGTM

2023-12-07 17:46 UTC, ericcurtin commented
On this @mwperina 

"ccount mwperina has no write access nor is author of PR!"

I added you as a member with write access, I think you just have to accept.

2023-12-08 09:23 UTC, mwperina commented
/packit test

2023-12-08 09:26 UTC, mwperina commented
/packit test

2023-12-08 09:27 UTC, mwperina commented
> On this @mwperina
> 
> "ccount mwperina has no write access nor is author of PR!"
> 
> I added you as a member with write access, I think you just have to accept.

I probably missed some email, but I was able to find out the invite in my organizations and it works fine.
Thanks Eric.

2023-12-08 19:22 UTC, Yarboa commented
There is an issue with reboot
```
            00:00:25 /integration/tests/boot-validation [1/1]
            00:00:25 errr /integration/tests/boot-validation (on default-0) (reboot timeout) [1/1]
        fail: Failed to pull workdir from the guest. This usually means that login as 'root' to the guest does not work
 ``` 
 I will have to reserve AWS and debug

2023-12-11 13:15 UTC, Yarboa commented
Ok i was running it manually, 
https://artifacts.dev.testing-farm.io/fc6e7439-35be-41b0-a5af-a40f4c2ca703/
It seems to be TF issue, lets wait to this PR to pass all tests

2023-12-13 16:30 UTC, ericcurtin commented
If we rebase this it might just work @Yarboa

2023-12-14 08:53 UTC, mwperina commented
I just noticed that RPMs are generated as they would be a stable release (`initoverlayfs-0.98-1.el9.src.rpm`) and not as a snapshot build (`initoverlayfs-0.98-0.202312131810.gitefcc221.el9.src.rpm`). That should be fixed, if we want to include those RPMs into some snaphot builds repo (for example under centos-automotive-sig group) and make them consumable for other testers

2023-12-14 09:56 UTC, Yarboa commented
> I just noticed that RPMs are generated as they would be a stable release (`initoverlayfs-0.98-1.el9.src.rpm`) and not as a snapshot build (`initoverlayfs-0.98-0.202312131810.gitefcc221.el9.src.rpm`). That should be fixed, if we want to include those RPMs into some snaphot builds repo (for example under centos-automotive-sig group) and make them consumable for other testers

@mwperina thanks
do you refer running to something like this ? build-scripts/version.sh

2023-12-14 10:15 UTC, mwperina commented
> > I just noticed that RPMs are generated as they would be a stable release (`initoverlayfs-0.98-1.el9.src.rpm`) and not as a snapshot build (`initoverlayfs-0.98-0.202312131810.gitefcc221.el9.src.rpm`). That should be fixed, if we want to include those RPMs into some snaphot builds repo (for example under centos-automotive-sig group) and make them consumable for other testers
> 
> @mwperina thanks do you refer running to something like this ? build-scripts/version.sh

So BlueChi has that support, so if you want to inspire, please take a look at those files:

https://github.com/eclipse-bluechi/bluechi/blob/main/build-scripts/build-rpm.sh
https://github.com/eclipse-bluechi/bluechi/blob/main/build-scripts/build-srpm.sh
https://github.com/eclipse-bluechi/bluechi/blob/main/build-scripts/create-archive.sh
https://github.com/eclipse-bluechi/bluechi/blob/main/build-scripts/create-spec.sh
https://github.com/eclipse-bluechi/bluechi/blob/main/build-scripts/version.sh

https://github.com/eclipse-bluechi/bluechi/blob/main/.packit.yml#L20

But maybe it can be simplifed for initoverlayfs, which is much smaller project

2023-12-14 10:19 UTC, Yarboa commented
> > > I just noticed that RPMs are generated as they would be a stable release (`initoverlayfs-0.98-1.el9.src.rpm`) and not as a snapshot build (`initoverlayfs-0.98-0.202312131810.gitefcc221.el9.src.rpm`). That should be fixed, if we want to include those RPMs into some snaphot builds repo (for example under centos-automotive-sig group) and make them consumable for other testers
> > 
> > 
> > @mwperina thanks do you refer running to something like this ? build-scripts/version.sh
> 
> So BlueChi has that support, so if you want to inspire, please take a look at those files:
> 
> https://github.com/eclipse-bluechi/bluechi/blob/main/build-scripts/build-rpm.sh https://github.com/eclipse-bluechi/bluechi/blob/main/build-scripts/build-srpm.sh
> 
> Above 2 files are not needed for packit, they are here for previous GH build/test integration and for local command line convenience.
> 
> Below files are required for packit integration: https://github.com/eclipse-bluechi/bluechi/blob/main/build-scripts/create-archive.sh https://github.com/eclipse-bluechi/bluechi/blob/main/build-scripts/create-spec.sh https://github.com/eclipse-bluechi/bluechi/blob/main/build-scripts/version.sh https://github.com/eclipse-bluechi/bluechi/blob/main/.packit.yml#L20
> 
> But maybe it can be simplifed for initoverlayfs, which is much smaller project

Thanks, much appreciated

2023-12-14 12:16 UTC, mwperina commented
Unfortunately it's not enough, you still need to convert spec file to a template and replace version/release in this template per build:
https://github.com/eclipse-bluechi/bluechi/blob/main/build-scripts/create-spec.sh

2023-12-14 12:24 UTC, ericcurtin approved these changes
LGTM, we can do follow on work in the next PR if this is green

2023-12-14 12:26 UTC, ericcurtin commented
I wish there was a auto-merge if build is green button here like we have in gitlab, it's useful...

2023-12-14 12:28 UTC, ericcurtin commented
I found it in settings and turned it on, maybe the next PR will have the option

2023-12-14 12:29 UTC, Yarboa commented
> Unfortunately it's not enough, you still need to convert spec file to a template and replace version/release in this template per build: https://github.com/eclipse-bluechi/bluechi/blob/main/build-scripts/create-spec.sh

Noticed that. yes, lets wait

2023-12-14 12:51 UTC, Yarboa commented
verified 'package_version': '0.98-0.202312141231.git4c998f9',

2023-12-14 12:51 UTC, merged